// Auto-generated — do not edit manually
export const ICON_KEYS = {
  1: { a: ["img_IAascendant.png"], b: ["img_USERascendant.png"] },
  2: { a: ["img_IAascendant.png"], b: ["img_USERascendant.png"] },
  3: { a: ["img_IAascendant.png"], b: ["img_USERascendant.png"] },
  4: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  5: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  6: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  7: { a: ["img_inclusivity.png"], b: ["img_equality.png"] },
  8: { a: ["img_bonpublic.png", "img_Gaspillage.png"], b: ["img_critique.png", "img_Frugalite.png"] },
  9: { a: ["img_bonpublic.png", "img_Gaspillage.png"], b: ["img_critique.png", "img_Frugalite.png"] },
  10: { a: ["img_equality.png"], b: ["img_bonpublic.png"] },
  11: { a: ["img_Duplicite.png"], b: ["img_Integrite.png"] },
  12: { a: ["img_Gaspillage.png"], b: ["img_Frugalite.png"] },
  13: { a: ["img_Gaspillage.png"], b: ["img_Frugalite.png"] },
  14: { a: ["img_USERascendant.png", "img_Gaspillage.png"], b: ["img_Integrite.png", "img_Frugalite.png"] },
  15: { a: ["img_USERascendant.png", "img_Gaspillage.png"], b: ["img_Integrite.png", "img_Frugalite.png"] },
  16: { a: ["img_USERascendant.png", "img_delestage.png"], b: ["img_Integrite.png", "img_MonteeCptces.png"] },
  17: { a: ["img_Duplicite.png"], b: ["img_Integrite.png"] },
  18: { a: ["img_data.png"], b: ["img_datacloud.png"] },
  19: { a: ["img_Gaspillage.png", "img_delestage.png"], b: ["img_Frugalite.png", "img_MonteeCptces.png"] },
  20: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  21: { a: ["img_Gaspillage.png"], b: ["img_Frugalite.png"] },
  22: { a: ["img_critique.png", "img_Gaspillage.png"], b: ["img_delestage.png", "img_Frugalite.png"] },
  23: { a: ["img_delestage.png", "img_Gaspillage.png"], b: ["img_MonteeCptces.png", "img_Frugalite.png"] },
  24: { a: ["img_USERascendant.png"], b: ["img_IAascendant.png"] },
  25: { a: ["img_datacloud.png"], b: ["img_data.png"] },
  26: { a: ["img_delestage.png", "img_IAascendant.png"], b: ["img_MonteeCptces.png", "img_USERascendant.png"] },
  27: { a: ["img_Integrite.png"], b: ["img_Duplicite.png"] },
  28: { a: ["img_bonpublic.png", "img_data.png"], b: ["img_critique.png", "img_datacloud.png"] },
  29: { a: ["img_IAascendant.png", "img_data.png"], b: ["img_Integrite.png", "img_datacloud.png"] },
  30: { a: ["img_BoiteNoire.png", "img_IAascendant.png"], b: ["img_Tsprence.png", "img_USERascendant.png"] },
  31: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  32: { a: ["img_Inegalite.png"], b: ["img_equality.png"] },
  33: { a: ["img_USERascendant.png", "img_Errors.png"], b: ["img_equality.png", "img_Integrite.png"] },
  34: { a: ["img_Integrite.png", "img_equality.png"], b: ["img_Integrite.png", "img_inclusivity.png"] },
  35: { a: ["img_Robbery.png"], b: ["img_critique.png"] },
  36: { a: ["img_IAascendant.png"], b: ["img_USERascendant.png"] },
  37: { a: ["img_bonpublic.png", "img_Inegalite.png"], b: ["img_critique.png", "img_inclusivity.png"] },
  38: { a: ["img_USERascendant.png", "img_inclusion.png"], b: ["img_USERascendant.png"] },
  39: { a: ["img_USERascendant.png", "img_inclusion.png"], b: ["img_USERascendant.png"] },
  40: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  41: { a: ["img_IAascendant.png"], b: ["img_USERascendant.png"] },
  42: { a: ["img_datacloud.png"], b: ["img_data.png"] },
  43: { a: ["img_Duplicite.png"], b: ["img_Integrite.png"] },
  44: { a: ["img_equality.png"], b: ["img_Inegalite.png"] },
  45: { a: ["img_Tsprence.png"], b: ["img_BoiteNoire.png"] },
  46: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  47: { a: ["img_MonteeCptces.png"], b: ["img_delestage.png"] },
  48: { a: ["img_Integrite.png"], b: ["img_Duplicite.png"] },
  49: { a: ["img_inclusivity.png"], b: ["img_Inegalite.png"] },
  50: { a: [], b: [] },
  51: { a: ["img_Frugalite.png"], b: ["img_Gaspillage.png"] },
  52: { a: ["img_Frugalite.png"], b: ["img_Gaspillage.png"] },
  53: { a: ["img_Frugalite.png"], b: ["img_Gaspillage.png"] },
  54: { a: ["img_Frugalite.png"], b: ["img_Gaspillage.png"] },
  55: { a: ["img_Gaspillage.png"], b: ["img_Frugalite.png"] },
  56: { a: ["img_Tsprence.png"], b: ["img_BoiteNoire.png"] },
  57: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  58: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  59: { a: ["img_IAascendant.png"], b: ["img_USERascendant.png"] },
  60: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  61: { a: ["img_datacloud.png"], b: ["img_data.png"] },
  62: { a: ["img_IAascendant.png"], b: ["img_USERascendant.png"] },
  63: { a: ["img_Integrite.png"], b: ["img_Duplicite.png"] },
  64: { a: ["img_IAascendant.png"], b: ["img_USERascendant.png"] },
  65: { a: ["img_datacloud.png"], b: ["img_data.png"] },
  66: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  67: { a: ["img_Frugalite.png"], b: ["img_Gaspillage.png"] },
  68: { a: ["img_data.png"], b: ["img_datacloud.png"] },
  69: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  70: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  71: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  72: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  73: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  74: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  75: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  76: { a: ["img_inclusivity.png"], b: ["img_Inegalite.png"] },
  77: { a: ["img_datacloud.png"], b: ["img_data.png"] },
  78: { a: ["img_datacloud.png"], b: ["img_data.png"] },
  79: { a: ["img_Integrite.png"], b: ["img_Duplicite.png"] },
  80: { a: ["img_MonteeCptces.png"], b: ["img_delestage.png"] },
  81: { a: ["img_datacloud.png"], b: ["img_data.png"] },
  82: { a: ["img_MonteeCptces.png"], b: ["img_delestage.png"] },
  83: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  84: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  85: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  86: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  87: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  88: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  89: { a: ["img_Duplicite.png"], b: ["img_Integrite.png"] },
  90: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  91: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  92: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  93: { a: ["img_IAascendant.png"], b: ["img_USERascendant.png"] },
  94: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  95: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  96: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  97: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  98: { a: ["img_IAascendant.png"], b: ["img_USERascendant.png"] },
  99: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  100: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
};

export const ICON_MAX = {
  "img_delestage.png": 26,
  "img_MonteeCptces.png": 25,
  "img_critique.png": 21,
  "img_bonpublic.png": 20,
  "img_USERascendant.png": 19,
  "img_Gaspillage.png": 16,
  "img_Frugalite.png": 16,
  "img_IAascendant.png": 14,
  "img_Integrite.png": 14,
  "img_datacloud.png": 11,
  "img_data.png": 11,
  "img_Duplicite.png": 8,
  "img_equality.png": 6,
  "img_inclusivity.png": 5,
  "img_Inegalite.png": 5,
  "img_Tsprence.png": 3,
  "img_BoiteNoire.png": 3,
  "img_inclusion.png": 2,
  "img_Errors.png": 1,
  "img_Robbery.png": 1,
};

export const BILAN_CARDS = [
  {
    img1: "img_bonpublic.png",
    title1: "Bon public",
    desc1: "Tu acceptes d'utiliser ces outils, sans trop te pr\u00e9occuper de leur fonctionnement ou de leurs limites. Tant qu'ils fonctionnent, le reste t'importe peu.",
    img2: "img_critique.png",
    title2: "Esprit critique",
    desc2: "Pas question d'utiliser des outils sans comprendre leurs enjeux. Il faut que tu comprennes tous les aspects, toutes les cons\u00e9quences de leur utilisation.",
  },
  {
    img1: "img_delestage.png",
    title1: "D\u00e9lestage cognitif",
    desc1: "Tu abandonnes \u00e0 l'IA des t\u00e2ches qui sont importantes pour le d\u00e9veloppement g\u00e9n\u00e9ral de tes comp\u00e9tences.",
    img2: "img_MonteeCptces.png",
    title2: "Mont\u00e9e en comp\u00e9tences",
    desc2: "Tu gardes la main sur le d\u00e9veloppement de tes comp\u00e9tences, en utilisant l'IA pour des t\u00e2ches pr\u00e9cises, mais pas essentielles.",
  },
  {
    img1: "img_Duplicite.png",
    title1: "Duplicit\u00e9",
    desc1: "Tu utilises l'IA de fa\u00e7on cach\u00e9e, sans la d\u00e9clarer et parfois, en faisant passer son travail pour le tien.",
    img2: "img_Integrite.png",
    title2: "Int\u00e9grit\u00e9",
    desc2: "Tu es transparent sur ton utilisation de l'IA. Tu la d\u00e9clares de fa\u00e7on honn\u00eate, en pr\u00e9cisant o\u00f9 et pourquoi tu l'as utilis\u00e9e.",
  },
  {
    img1: "img_IAascendant.png",
    title1: "L'IA prend l'ascendant",
    desc1: "L'IA ma\u00eetrise ton processus d'apprentissage, parce qu'il est enti\u00e8rement automatis\u00e9, ou que tu n'interviens plus pour contr\u00f4ler son fonctionnement.",
    img2: "img_USERascendant.png",
    title2: "L'utilisateur garde l'ascendant",
    desc2: "Tu restes en contr\u00f4le : tu ne laisses pas l'IA faire toutes les t\u00e2ches, sans que tu v\u00e9rifies ou que tu critiques ce qu'elle fait.",
  },
  {
    img1: "img_Time.png",
    title1: "Temps",
    desc1: "L'usage de l'IA est motiv\u00e9 par le gain de temps : certaines t\u00e2ches sont faites automatiquement et sans effort.",
    img2: "img_inclusion.png",
    title2: "\u00c9tayage et inclusion",
    desc2: "En s'appuyant sur un profil personnalis\u00e9, l'IA est capable d'adapter ses r\u00e9ponses \u00e0 l'utilisateur. Elle peut aussi compenser certaines de ses difficult\u00e9s.",
  },
  {
    img1: "img_Robbery.png",
    title1: "Pillage",
    desc1: "L'utilisation de l'IA ne respecte pas les droits des auteurs. M\u00eame si elle transforme ces sources, elle les utilise sans citer et sans r\u00e9tribuer les cr\u00e9ateurs.",
    img2: "img_Time.png",
    title2: "Respect des droits",
    desc2: "Tu es conscient que l'IA peut utiliser des sources prot\u00e9g\u00e9es par des droits d'auteur. Pour toi, c'est un aspect important.",
  },
  {
    img1: "img_Frugalite.png",
    title1: "Frugalit\u00e9 / \u00e9conomie",
    desc1: "Tes choix montrent une volont\u00e9 de ne pas gaspiller les ressources naturelles.",
    img2: "img_Gaspillage.png",
    title2: "Gaspillage",
    desc2: "Ta pratique r\u00e9p\u00e9t\u00e9e ou maladroite de l'IA consomme beaucoup de ressources naturelles et impacte l'environnement.",
  },
  {
    img1: "img_BoiteNoire.png",
    title1: "Bo\u00eete noire",
    desc1: "Tu ne sais pas comment fonctionnent les outils d'IA. Ces outils sont comme des \"bo\u00eetes noires\" qui agissent de fa\u00e7on un peu magique.",
    img2: "img_Tsprence.png",
    title2: "Transparence de fonctionnement",
    desc2: "Pour toi, il est essentiel que tu comprennes le fonctionnement, pour que tu utilises ces outils de fa\u00e7on r\u00e9fl\u00e9chie.",
  },
  {
    img1: "img_equality.png",
    title1: "\u00c9galitaire",
    desc1: "Tu es d'accord pour dire que l'IA doit s'adresser \u00e0 tout le monde. Elle doit s'adapter aux minorit\u00e9s, aux personnes en difficult\u00e9.",
    img2: "img_Inegalite.png",
    title2: "In\u00e9galitaire",
    desc2: "On ne pourra pas faire en sorte que l'IA soit utilis\u00e9e par tout le monde de la m\u00eame mani\u00e8re. Tant pis si \u00e7a doit cr\u00e9er ou empirer les in\u00e9galit\u00e9s.",
  },
  {
    img1: "img_datacloud.png",
    title1: "S\u00e9curit\u00e9 des donn\u00e9es",
    desc1: "Les donn\u00e9es d'entra\u00eenement ou d'utilisation de l'IA doivent \u00eatre v\u00e9rifi\u00e9es. On r\u00e9duit ainsi le risque d'erreur ou l'usage de donn\u00e9es non autoris\u00e9es.",
    img2: "img_data.png",
    title2: "Open Data",
    desc2: "Peu importe les donn\u00e9es utilis\u00e9es par l'IA. Plus il y en a, plus les r\u00e9sultats seront pertinents, selon toi.",
  },
  {
    img1: "img_CultureRespect.png",
    title1: "Respect des cultures",
    desc1: "Tu sais que l'IA favorise certaines cultures. Elle poss\u00e8de des biais culturels. Tu aimerais qu'elle prenne en compte davantage de cultures.",
    img2: "img_CultureHegemonie.png",
    title2: "Culture h\u00e9g\u00e9monique",
    desc2: "L'IA se nourrit surtout des cultures de langue anglaise. Il faut accepter que certaines cultures soient majoritaires.",
  },
  {
    img1: "img_IAascendant.png",
    title1: "L'IA prend l'ascendant",
    desc1: "L'IA ma\u00eetrise ton processus d'apprentissage, parce qu'il est enti\u00e8rement automatis\u00e9.",
    img2: "img_USERascendant.png",
    title2: "L'utilisateur garde l'ascendant",
    desc2: "Tu restes en contr\u00f4le : tu ne laisses pas l'IA faire toutes les t\u00e2ches sans que tu v\u00e9rifies ce qu'elle fait.",
  },
];
